/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import java.util.List;

/**
 * the list of pages.
 */
@JacksonXmlRootElement(localName = "PageList")
public final class PageList {
    private static final class PageRangeWrapper {
        @JacksonXmlProperty(localName = "PageRange")
        private final List<PageRange> items;

        @JsonCreator
        private PageRangeWrapper(@JacksonXmlProperty(localName = "PageRange") List<PageRange> items) {
            this.items = items;
        }
    }

    /**
     * The pageRange property.
     */
    @JacksonXmlProperty(localName = "PageRange")
    private PageRangeWrapper pageRange;

    private static final class ClearRangeWrapper {
        @JacksonXmlProperty(localName = "ClearRange")
        private final List<ClearRange> items;

        @JsonCreator
        private ClearRangeWrapper(@JacksonXmlProperty(localName = "ClearRange") List<ClearRange> items) {
            this.items = items;
        }
    }

    /**
     * The clearRange property.
     */
    @JacksonXmlProperty(localName = "ClearRange")
    private ClearRangeWrapper clearRange;

    /**
     * Get the pageRange value.
     *
     * @return the pageRange value.
     */
    public List<PageRange> pageRange() {
        return this.pageRange.items;
    }

    /**
     * Set the pageRange value.
     *
     * @param pageRange the pageRange value to set.
     * @return the PageList object itself.
     */
    public PageList withPageRange(List<PageRange> pageRange) {
        this.pageRange = new PageRangeWrapper(pageRange);
        return this;
    }

    /**
     * Get the clearRange value.
     *
     * @return the clearRange value.
     */
    public List<ClearRange> clearRange() {
        return this.clearRange.items;
    }

    /**
     * Set the clearRange value.
     *
     * @param clearRange the clearRange value to set.
     * @return the PageList object itself.
     */
    public PageList withClearRange(List<ClearRange> clearRange) {
        this.clearRange = new ClearRangeWrapper(clearRange);
        return this;
    }
}
