/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for DeleteSnapshotsOption.
 */
public enum DeleteSnapshotsOption {
    /** Enum value include. */
    INCLUDE("include"),

    /** Enum value only. */
    ONLY("only");

    /** The actual serialized value for a DeleteSnapshotsOption instance. */
    private String value;

    DeleteSnapshotsOption(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a DeleteSnapshotsOption instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed DeleteSnapshotsOption object, or null if unable to parse.
     */
    @JsonCreator
    public static DeleteSnapshotsOption fromString(String value) {
        DeleteSnapshotsOption[] items = DeleteSnapshotsOption.values();
        for (DeleteSnapshotsOption item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
