/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Error model.
 */
public class Error {
    /**
     * The code property.
     */
    @JsonProperty(value = "Code", required = true)
    private String code;

    /**
     * The message property.
     */
    @JsonProperty(value = "Message", required = true)
    private String message;

    /**
     * The exceptionDetails property.
     */
    @JsonProperty(value = "ExceptionDetails")
    private ErrorExceptionDetails exceptionDetails;

    /**
     * Get the code value.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the code value.
     *
     * @param code the code value to set
     * @return the Error object itself.
     */
    public Error withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the Error object itself.
     */
    public Error withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the exceptionDetails value.
     *
     * @return the exceptionDetails value
     */
    public ErrorExceptionDetails exceptionDetails() {
        return this.exceptionDetails;
    }

    /**
     * Set the exceptionDetails value.
     *
     * @param exceptionDetails the exceptionDetails value to set
     * @return the Error object itself.
     */
    public Error withExceptionDetails(ErrorExceptionDetails exceptionDetails) {
        this.exceptionDetails = exceptionDetails;
        return this;
    }

}
