/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for GeoReplicationStatusType.
 */
public enum GeoReplicationStatusType {
    /** Enum value live. */
    LIVE("live"),

    /** Enum value bootstrap. */
    BOOTSTRAP("bootstrap"),

    /** Enum value unavailable. */
    UNAVAILABLE("unavailable");

    /** The actual serialized value for a GeoReplicationStatusType instance. */
    private String value;

    GeoReplicationStatusType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a GeoReplicationStatusType instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed GeoReplicationStatusType object, or null if unable to parse.
     */
    @JsonCreator
    public static GeoReplicationStatusType fromString(String value) {
        GeoReplicationStatusType[] items = GeoReplicationStatusType.values();
        for (GeoReplicationStatusType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
